<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Sales\Block\Adminhtml\Order\View\Items $block */
/** @var $viewModel Epay\DeliveryDate\ViewModel\DeliveryDate */
$_order = $block->getOrder();
$viewModel = $block->getViewModel(); ?>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
        <tr class="headings">
            <?php $i = 0;
            $columns = $block->getColumns();
            $lastItemNumber = count($columns);
            if ($viewModel->showDeliveryDate()) {
                $lastItemNumber++;
            }
            ?>
            <?php foreach ($columns as $columnName => $columnTitle) : ?>
                <?php $i++; ?>
                <th class="col-<?= $block->escapeHtmlAttr($columnName) ?><?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>"><span><?= $block->escapeHtml($columnTitle) ?></span></th>
            <?php endforeach; ?>
            <?php
            if ($viewModel->showDeliveryDate()) {
                $i++; ?>
                <th class="col-<?= $block->escapeHtmlAttr('Delivery Date') ?><?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>"><span><?= $block->escapeHtml('Delivery Date') ?></span></th>
            <?php } ?>
        </tr>
        </thead>
        <?php $_items = $block->getItemsCollection();?>
        <?php $i = 0; foreach ($_items as $_item) : ?>
            <?php if ($_item->getParentItem()) :
                continue;
            else :
                $i++;
            endif; ?>
            <tbody class="<?= /* @noEscape */ $i%2 ? 'even' : 'odd' ?>">
            <?= $block->getItemHtml($_item) ?>
            <?= $block->getItemExtraInfoHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
